global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

remote_write:
  - url: "https://osherlevi7777.grafana.net/api/dashboards/home"
    basic_auth:
      username: "osherlevi7777"
      password: "eyJrIjoib2VZcmk2YURxRk5tc1VRb1V0R0dBWWp6UTRUWTdQV3kiLCJuIjoiZ3JhZmFuYS1wcm9tZXRodXMiLCJpZCI6MX0"